spring:
  application:
    name: claimhub
  profiles:
    default: dev
  jpa:
    open-in-view: false
  jackson:
    default-property-inclusion: non_null

server:
  error:
    include-message: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: ClaimHub
    description: Claim management microservice
    version: 0.0.1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
